
# path to sample sheet
samples: config/samples_Brugia_malayi_present.tsv

# name of output directory
output_dir: results_Brugia_malayi

# path of kraken standard db
# kraken_standard: /workspaces/groups/database/kraken2-standard-db/kraken2_standard

# path of kraken nt db
kraken_nt: /workspaces/groups/database/nt-2022-11-14_kraken/ncbi_nt/

# path of kraken silva database
kraken_silva: /workspaces/groups/database/silva132-2023-05-24-kraken/16S_SILVA132_k2db/

# number of threads to use
threads: 6

