
# path to sample sheet
samples: config/samples.tsv

# name of output directory
output_dir: results

# path of kraken db
kraken_db: /workspaces/groups/database/kraken2-standard-db/kraken2_standard

# number of threads to use
threads: 6

